= Gravitee.io Blog Resources

ifdef::env-github[]
image:https://badges.gitter.im/Join Chat.svg["Gitter", link="https://gitter.im/gravitee-io/gravitee-io?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
endif::[]

Gravitee resource files used in various blogs.

This repository contains also some Postman collections that can be executed to demonstrate some features of the Gravitee solution.

*DISCLAIMER: postman collections only works with the nightly version of the Gravitee platform which is not stable yet !*

== Requirement

=== Docker

You must have
  http://docs.docker.com/installation/[Docker] and
  http://docs.docker.com/compose/install/[Docker Compose]
installed on your machine:

```bash
$ docker --version
$ docker-compose --version
```

=== Newman

You'll also need to install `newman` command.

Using NPM:

```bash
$ npm install -g newman
```

Using Homebrew:

```bash
$ brew install newman
```

=== Gravitee's hosts

By default, API Management is exposed on https://apim.gravitee.io and Access Management is exposed on https://am.gravitee.io
Add these domains to your own /etc/hosts file:

```bash
$ sudo vi /etc/hosts
127.0.0.1       localhost apim.gravitee.io am.gravitee.io
```

== The postman collection

Multiple postman collections are available:

 - `5-minutes-to-secure-an-API-with-gravitee-stack`: declares the Swagger Pet Store API on Gravitee APIM with a restricted keyless plan and an unlocked Oauth2 plan.
 - To be continued...

== Launch a case

First, you need to start the Gravitee stack by typing this command:

```bash
curl -L http://bit.ly/graviteeio-platform | bash -s -- --nightly
```

Clone this repo and run the following command:

```bash
$ newman run -k \
    -e postman-env/Gravitee.io-Local-Docker-Compose-Environment.json \
    5-minutes-to-secure-an-API-with-gravitee-stack/postman_collection.json
```

Next, have a look at the APIM and AM portals to get more details.